# Generated by Django 5.0.1 on 2024-03-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('actual_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='productimg')),
                ('p_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brandmodel')),
                ('p_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.categorymodel')),
            ],
        ),
    ]
