# Generated by Django 5.0.1 on 2024-03-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
