# Generated by Django 5.0.1 on 2024-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cartmodel_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='areacode',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='lname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='zipcode',
            field=models.IntegerField(default=None),
        ),
    ]
