# Generated by Django 5.0.1 on 2024-03-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_productdescriptionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdescriptionmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='productdescriptionmodel',
            name='camera',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='productdescriptionmodel',
            name='cameradescription',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='productdescriptionmodel',
            name='design',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='productdescriptionmodel',
            name='designdescription',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='productdescriptionmodel',
            name='technology',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='productdescriptionmodel',
            name='technologydescription',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='productdescriptionmodel',
            name='titledescription',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='productdescriptionmodel',
            name='touch',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='productdescriptionmodel',
            name='touchdescription',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='productdescriptionmodel',
            name='title',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
