# Generated by Django 5.0.1 on 2024-03-27 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_title_productmodel_titleproduct_reviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='titleproduct',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.productmodel'),
        ),
    ]
