# Generated by Django 5.0.1 on 2024-03-27 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_reviewmodel_titleproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='titleproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productmodel'),
        ),
    ]
